# Generated by Django 6.0.5 on 2026-05-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('module', models.CharField(choices=[('USB', 'Unified Strategy Builder'), ('ISE', 'Indicator Signal Engine'), ('ISB', 'Inbound Signal Bridge')], db_index=True, max_length=10)),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('user_message', models.TextField()),
                ('ai_response', models.TextField()),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=8, default=0, max_digits=12)),
                ('cost_inr', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('model_used', models.CharField(default='', max_length=100)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
