# Generated by Django 6.0.5 on 2026-06-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_logs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BearerToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bearer Token',
            },
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='module',
            field=models.CharField(choices=[('USB', 'Unified Strategy Builder'), ('ISE', 'Indicator Signal Engine'), ('ISB', 'Inbound Signal Bridge'), ('RES', 'Rapid Execution Scalper'), ('MLH', 'Multi-Leg Hedger')], db_index=True, max_length=10),
        ),
    ]
