# Generated by Django 6.0.5 on 2026-06-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_logs', '0002_bearer_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='APICallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('module', models.CharField(choices=[('USB', 'Unified Strategy Builder'), ('ISE', 'Indicator Signal Engine'), ('ISB', 'Inbound Signal Bridge'), ('RES', 'Rapid Execution Scalper'), ('MLH', 'Multi-Leg Hedger'), ('SHARED', 'Shared Service')], db_index=True, max_length=10)),
                ('call_type', models.CharField(db_index=True, max_length=100)),
                ('endpoint', models.CharField(max_length=500)),
                ('method', models.CharField(default='POST', max_length=10)),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('duration_ms', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('connection_error', 'Connection Error')], db_index=True, default='success', max_length=20)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=100)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
